# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
