# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_qrcode_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='browser',
            field=models.CharField(default=1, max_length=50, verbose_name='Navegador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='ip',
            field=models.CharField(default=2, max_length=30, verbose_name='Dirección Ip'),
            preserve_default=False,
        ),
    ]
