# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171007_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='os',
            field=models.CharField(default=1, max_length=50, verbose_name='Sistema Operativo'),
            preserve_default=False,
        ),
    ]
